- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      force: true
      recursive: true

- link:
    # Universal

    ~/.config/nvim:
      path: universal/nvim
      force: true
    ~/.zshrc:
      path: universal/zshrc
      force: true
    ~/.zsh:
      path: universal/zsh
      force: true
    ~/.bash_logout:
      path: universal/bash/bash_logout
      force: true
    ~/.wezterm.lua:
      path: universal/wezterm/wezterm.lua
      force: true
    ~/.bash_profile:
      path: universal/bash/bash_profile
      force: true
    ~/.bashrc:
      path: universal/bash/bashrc
      force: true
    ~/.config/kitty:
      path: universal/kitty
      force: true
    ~/.config/Code/User/settings.json:
      path: universal/code/settings.json
      force: true
    ~/.config/Code - OSS/User/settings.json:
      path: universal/code/settings.json
      force: true
    ~/.config/VSCodium/User/settings.json:
      path: universal/code/settings.json
      force: true
    ~/.gitconfig:
      path: universal/git/gitconfig
      force: true
    ~/.config/btop:
      path: universal/btop
      force: true
    ~/.config/neofetch:
      path: universal/neofetch
      force: true
    ~/.tmux.conf:
      path: universal/tmux/tmux.conf
      force: true
    ~/package.json:
      path: universal/node/package.json
      force: true
    ~/tsconfig.json:
      path: universal/node/tsconfig.json
      force: true
    ~/.editorconfig:
      path: universal/editorconfig/editorconfig
    ~/.config/nushell:
      path: universal/nushell
      force: true
    ~/.config/alacritty:
      path: universal/alacritty
      force: true

    # Darwin (macOS)

    ~/.config/skhd:
      if: "[ `uname` = Darwin ]"
      path: darwin/skhd
      force: true
    ~/.config/yabai:
      if: "[ `uname` = Darwin ]"
      path: darwin/yabai
      force: true
    ~/Brewfile:
      if: "[ `uname` = Darwin ]"
      path: darwin/brew/Brewfile
      force: true

      # Linux

    ~/.config/copyq/copyq.conf:
      if: "[ `uname` != Darwin ]"
      path: linux/copyq/copyq.conf
      force: true
    ~/.config/fontconfig:
      if: "[ `uname` != Darwin ]"
      path: linux/fontconfig
      force: true
    ~/.config/foot:
      if: "[ `uname` != Darwin ]"
      path: linux/foot
      force: true
    ~/.config/gtk-3.0:
      if: "[ `uname` != Darwin ]"
      path: linux/gtk3
      force: true
    ~/.config/gtk-4.0:
      if: "[ `uname` != Darwin ]"
      path: linux/gtk4
      force: true
    ~/.config/hypr:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland
      force: true
    ~/.config/gtklock:
      if: "[ `uname` != Darwin ]"
      path: linux/gtklock
      force: true
    ~/.config/guvcview2:
      if: "[ `uname` != Darwin ]"
      path: linux/guvcview/guvcview2
      force: true
    ~/default.gpfl:
      if: "[ `uname` != Darwin ]"
      path: linux/guvcview/default.gpfl
      force: true
    ~/.config/Kvantum:
      if: "[ `uname` != Darwin ]"
      path: linux/kvantum
      force: true
    ~/.config/latte:
      if: "[ `uname` != Darwin ]"
      path: linux/latte
      force: true
    ~/.config/swaync:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland/swaync
      force: true
    ~/.config/mimeapps.list:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/mimeapps.list
      force: true
    ~/.config/nwg-look:
      if: "[ `uname` != Darwin ]"
      path: linux/nwg-look
      force: true
    ~/.config/nwg-displays:
      if: "[ `uname` != Darwin ]"
      path: linux/nwg-displays
      force: true
    ~/.config/qt5ct:
      if: "[ `uname` != Darwin ]"
      path: linux/qt5ct
      force: true
    ~/.config/qt6ct:
      if: "[ `uname` != Darwin ]"
      path: linux/qt6ct
      force: true
    ~/.config/swappy:
      if: "[ `uname` != Darwin ]"
      path: linux/swappy
      force: true
    ~/.config/Thunar:
      if: "[ `uname` != Darwin ]"
      path: linux/thunar
      force: true
    ~/.config/xdg-terminals.list:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/xdg-terminals.list
      force: true
    ~/.config/user-dirs.dirs:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/user-dirs.dirs
      force: true
    ~/.config/user-dirs.locale:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/user-dirs.locale
      force: true
    ~/.config/xsettingsd.conf:
      if: "[ `uname` != Darwin ]"
      path: linux/x11/xsettingsd.conf
      force: true
    ~/.config/systemd/user:
      if: "[ `uname` != Darwin ]"
      path: linux/systemd
      force: true
    ~/.config/yay:
      if: "[ `uname` != Darwin ]"
      path: linux/yay
      force: true
    ~/.config/xfce4:
      if: "[ `uname` != Darwin ]"
      path: linux/xfce4
      force: true
    ~/.config/autostart:
      if: "[ `uname` != Darwin ]"
      path: linux/autostart
      force: true
    ~/.gtkrc-2.0:
      if: "[ `uname` != Darwin ]"
      path: linux/gtk2/gtkrc-2.0
      force: true
    ~/.config/lutris:
      if: "[ `uname` != Darwin ]"
      path: linux/lutris
      force: true
    # ~/wallpapers:
    #   if: "[ `uname` != Darwin ]"
    #   path: linux/hyprland/wallpapers
    #   force: true
    ~/.Xresources:
      if: "[ `uname` != Darwin ]"
      path: linux/x11/Xresources
      force: true
    ~/.thunderbird/profiles.ini:
      if: "[ `uname` != Darwin ]"
      path: linux/thunderbird/profiles.ini
      force: true
    ~/.thunderbird/installs.ini:
      if: "[ `uname` != Darwin ]"
      path: linux/thunderbird/installs.ini
      force: true
    ~/.nvidia-settings-rc:
      if: "[ `uname` != Darwin ]"
      path: linux/nvidia/nvidia-settings-rc
      force: true
    ~/.config/waybar:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland/waybar
      force: true
    ~/.config/wofi:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland/wofi
      force: true
    ~/.local/bin:
      if: "[ `uname` != Darwin ]"
      path: linux/bin
      force: true
    ~/.config/i3:
      if: "[ `uname` != Darwin ]"
      path: linux/i3
      force: true
    ~/.config/polybar:
      if: "[ `uname` != Darwin ]"
      path: linux/polybar
      force: true
    ~/.config/rofi:
      if: "[ `uname` != Darwin ]"
      path: linux/rofi
      force: true

    # # electron flag nonsense
    # ~/.config/electron-flags.conf:
    #   path: linux/electron/electron-flags.conf
    #   force: true
    # ~/.config/code-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    #   force: true
    # ~/.config/chromium-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    #   force: true
    # ~/.config/chrome-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    # ~/.config/edge-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    #   force: true
    # ~/.config/vscodium-flags.conf:
    #   path: linux/electron/electron-flags.conf
    #   force: true
    # ~/.config/electron24-flags.conf:
    #   path: linux/electron/electron-flags.conf
    #   force: true
    # ~/.config/electron25-flags.conf:
    #   path: linux/electron/electron-flags.conf
    #   force: true
    # ~/.config/electron26-flags.conf:
    #   path: linux/electron/electron-flags.conf
    #   force: true
    # ~/.config/electron27-flags.conf:
    #   path: linux/electron/electron-flags.conf
    #   force: true
    # ~/.config/edge-flags.conf:
    #   path: linux/electron/electron-flags.conf
    #   force: true
