- defaults:
    link:
      create: true
      relink: true
      force: true

- clean:
    ~/:
      force: true
    ~/.config:
      force: true
      recursive: true
    ~/.local/bin:
      force: true
      recursive: true

- link:
    # Scripts

    ~/.local/bin:
      path: bin

    # Neovim

    ~/.config/nvim:
      path: shell/nvim

    # Shell

    ~/.zshrc:
      path: shell/zshrc
    ~/.zsh:
      path: shell/zsh
    ~/.bash_logout:
      path: shell/bash/bash_logout
    ~/.bash_profile:
      path: shell/bash/bash_profile
    ~/.bashrc:
      path: shell/bash/bashrc
    ~/.tmux.conf:
      path: shell/tmux/tmux.conf
    ~/.gitconfig:
      path: shell/git/gitconfig
    ~/.ssh/config:
      path: shell/ssh/config

      # Universal

    ~/.wezterm.lua:
      path: universal/wezterm/wezterm.lua
    ~/.config/kitty:
      path: universal/kitty
    ~/.config/Code/User/settings.json:
      path: universal/code/settings.json
    ~/.config/Code - OSS/User/settings.json:
      path: universal/code/settings.json
    ~/.config/VSCodium/User/settings.json:
      path: universal/code/settings.json
    ~/package.json:
      path: universal/node/package.json
    ~/tsconfig.json:
      path: universal/node/tsconfig.json
    ~/.editorconfig:
      path: universal/editorconfig/editorconfig
    ~/.config/alacritty:
      path: universal/alacritty

    # Darwin (macOS)

    ~/.config/skhd:
      if: "[ `uname` = Darwin ]"
      path: darwin/skhd
    ~/.config/yabai:
      if: "[ `uname` = Darwin ]"
      path: darwin/yabai
    ~/Brewfile:
      if: "[ `uname` = Darwin ]"
      path: darwin/brew/Brewfile

      # Linux

    ~/.config/copyq/copyq.conf:
      if: "[ `uname` != Darwin ]"
      path: linux/copyq/copyq.conf
    ~/.config/fontconfig:
      if: "[ `uname` != Darwin ]"
      path: linux/fontconfig
    ~/.config/foot:
      if: "[ `uname` != Darwin ]"
      path: linux/foot
    ~/.gtkrc-2.0:
      if: "[ `uname` != Darwin ]"
      path: linux/gtk2/gtkrc-2.0
    ~/.config/gtk-2.0:
      if: "[ `uname` != Darwin ]"
      path: linux/gtk2
    ~/.config/gtk-3.0:
      if: "[ `uname` != Darwin ]"
      path: linux/gtk3
    ~/.config/gtk-4.0:
      if: "[ `uname` != Darwin ]"
      path: linux/gtk4
    ~/.config/hypr:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland
    ~/.config/gtklock:
      if: "[ `uname` != Darwin ]"
      path: linux/gtklock
    ~/.config/guvcview2:
      if: "[ `uname` != Darwin ]"
      path: linux/guvcview/guvcview2
    ~/default.gpfl:
      if: "[ `uname` != Darwin ]"
      path: linux/guvcview/default.gpfl
    ~/.config/Kvantum:
      if: "[ `uname` != Darwin ]"
      path: linux/kvantum
    ~/.config/latte:
      if: "[ `uname` != Darwin ]"
      path: linux/latte
    ~/.config/swaync:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland/swaync
    ~/.config/mimeapps.list:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/mimeapps.list
    ~/.config/nwg-look:
      if: "[ `uname` != Darwin ]"
      path: linux/nwg-look
    ~/.config/nwg-displays:
      if: "[ `uname` != Darwin ]"
      path: linux/nwg-displays
    ~/.config/qt5ct:
      if: "[ `uname` != Darwin ]"
      path: linux/qt5ct
    ~/.config/qt6ct:
      if: "[ `uname` != Darwin ]"
      path: linux/qt6ct
    ~/.config/swappy:
      if: "[ `uname` != Darwin ]"
      path: linux/swappy
    ~/.config/Thunar:
      if: "[ `uname` != Darwin ]"
      path: linux/thunar
    ~/.config/xdg-terminals.list:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/xdg-terminals.list
    ~/.config/user-dirs.dirs:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/user-dirs.dirs
    ~/.config/user-dirs.locale:
      if: "[ `uname` != Darwin ]"
      path: linux/xdg/user-dirs.locale
    ~/.config/xsettingsd:
      if: "[ `uname` != Darwin ]"
      path: linux/xsettingsd
    ~/.config/xsettingsd.conf:
      if: "[ `uname` != Darwin ]"
      path: linux/xsettingsd/xsettingsd.conf
    ~/.config/systemd/user:
      if: "[ `uname` != Darwin ]"
      path: linux/systemd
    ~/.config/yay:
      if: "[ `uname` != Darwin ]"
      path: linux/yay
    ~/.config/xfce4:
      if: "[ `uname` != Darwin ]"
      path: linux/xfce4
    ~/.config/autostart:
      if: "[ `uname` != Darwin ]"
      path: linux/autostart
    ~/.config/lutris:
      if: "[ `uname` != Darwin ]"
      path: linux/lutris
    # ~/wallpapers:
    #   if: "[ `uname` != Darwin ]"
    #   path: linux/hyprland/wallpapers
    ~/.Xresources:
      if: "[ `uname` != Darwin ]"
      path: linux/xresources/Xresources
    ~/.thunderbird/profiles.ini:
      if: "[ `uname` != Darwin ]"
      path: linux/thunderbird/profiles.ini
    ~/.thunderbird/installs.ini:
      if: "[ `uname` != Darwin ]"
      path: linux/thunderbird/installs.ini
    ~/.nvidia-settings-rc:
      if: "[ `uname` != Darwin ]"
      path: linux/nvidia/nvidia-settings-rc
    ~/.config/waybar:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland/waybar
    ~/.config/wofi:
      if: "[ `uname` != Darwin ]"
      path: linux/hyprland/wofi
    # # electron flag nonsense
    # ~/.config/electron-flags.conf:
    #   path: linux/electron/electron-flags.conf
    # ~/.config/code-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    # ~/.config/chromium-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    # ~/.config/chrome-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    # ~/.config/edge-flags.conf:
    #   path: linux/electron/chromium-flags.conf
    # ~/.config/vscodium-flags.conf:
    #   path: linux/electron/electron-flags.conf
    # ~/.config/electron24-flags.conf:
    #   path: linux/electron/electron-flags.conf
    # ~/.config/electron25-flags.conf:
    #   path: linux/electron/electron-flags.conf
    # ~/.config/electron26-flags.conf:
    #   path: linux/electron/electron-flags.conf
    # ~/.config/electron27-flags.conf:
    #   path: linux/electron/electron-flags.conf
    # ~/.config/edge-flags.conf:
    #   path: linux/electron/electron-flags.conf
