#!/bin/zsh

set -e # exit immediately if a command exits with a non-zero status

CONFIG="config.yaml"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install yay
if ! command -v yay &> /dev/null; then
  cd ~ && pacman -S --noconfirm --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si
fi

# Install zsh if not installed
if ! command -v zsh &> /dev/null; then
  yay -S --noconfirm --needed zsh
fi

yay -S --noconfirm --needed dotbot
yay -S --noconfirm --needed oh-my-zsh-git oh-my-zsh-autosuggestions-git oh-my-syntax-highlighting-git
yay -S --noconfirm --needed whitesur-cursor-theme-git whitesur-gtk-theme-git whitesur-icon-theme-git

cd ~ && git clone https://github.com/vinceliuice/WhiteSur-kde && cd WhiteSur-kde && ./install.sh || {
  echo "Error: WhiteSur-kde installation failed!"
  # exit 1
}

cd ~ && git clone https://github.com/hyprwm/contrib && cd contrib || {
  echo "Error: contrib installation failed!"
  # exit 1
}

cd hyprprop && sudo make install || {
  echo "Error: hyprprop installation failed!"
  # exit 1
}

cd grimblast && sudo make install || {
  echo "Error: grimblast installation failed!"
  # exit 1
}

cd hdrop && sudo make install || {
  echo "Error: hdrop installation failed!"
  # exit 1
}

cd scratchpad && sudo make install || {
  echo "Error: scratchpad installation failed!"
  # exit 1
}

cd shellevents && sudo make install || {
  echo "Error: shellevents installation failed!"
  # exit 1
}

cd try_swap_workspace && sudo make install || {
  echo "Error: try_swap_workspace installation failed!"
  # exit 1
}

cd "${BASEDIR}"

# Install dotfiles
dotbot -d "${BASEDIR}" -c "${CONFIG}" "${@}" || {
  echo "Error: Dotbot installation failed!"
  exit 1
}

cd ~/.local/bin && chmod u+r+x * && cd ~

cd "${BASEDIR}"

# Update the system
sudo pacman -Syu --noconfirm

# Check if the file exists
# if [ -f "packages.txt" ]; then
#   # Read the package names from the file and install them
#   while read -r package; do
#     yay -S --noconfirm --needed "$package"
#   done < packages.txt
#   echo "All user-installed packages have been installed."
# else
#   echo "The file 'packages.txt' does not exist."
# fi

# Update the package list
yay -Qqe > packages.txt

# Ensure services are enabled
sudo systemctl enable nvidia-persistenced.service
sudo systemctl enable nvidia-suspend.service
sudo systemctl enable nvidia-resume.service
sudo systemctl enable nvidia-hibernate.service

hyprctl reload

# Update mkinitcpio and grub
sudo update-grub
sudo mkinitcpio --config /etc/mkinitcpio.conf --generate /boot/initramfs-custom.img

# Update dotfiles repo
git add . || true
git commit -m "update dotfiles" || true
git push origin main
